name: 'Azure SQL Auto-Deploy'
description: 'Deploy SQL script or folder to Azure SQL database'
inputs:
  server-name:
    description: 'Name of the Azure SQL Server name, like Fabrikam.database.windows.net.'
    required: true
  connection-string:
    description:  'The connection string, including authentication information, for the Azure SQL Server database.'
    required: true
  dacpac-package:
    description: 'Path to DACPAC file. *.dacpac or a folder to deploy'
  sql-file:
    description: 'Path to SQL script file. *.sql or a folder to deploy'
  sql-folder:
    description: 'Path to SQL folder to deploy'
  arguments:
    description: 'In case DACPAC option is selected, additional SqlPackage.exe arguments that will be applied. When SQL query option is selected, additional sqlcmd.exe arguments will be applied.'
branding:
  icon: 'layers'
  color: 'yellow'
runs:
  using: 'node12'
  main: 'lib/main.js'
